#!/bin/bash
# Description
echo -e "\nVoiceRecogniseBot Script"
echo -e "\nThis script allows you to recognize voice commands."
echo -e "It also creates a symlink for easy access.\n"

# Create a symlink
sudo ln -s /opt/VoiceRecogniseBot/VoiceRecogniseBot /usr/bin/VoiceRecogniseBot

echo -e "Symlink created: /usr/bin/VoiceRecogniseBot -> /opt/VoiceRecogniseBot/VoiceRecogniseBot"



directory="/etc/voicerecognisebot"
file="$directory/appsettings.json"

if [ ! -d "$directory" ]; then
    mkdir -p "$directory"
fi

if [ ! -e "$file" ]; then
    echo '{}' > "$file"
fi


echo "Empty config created" 
echo "Use  VoiceRecogniseBot --command update_config to fill"

# Check if the script is running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root."
    sudo -s
fi

# Specify the service unit file path
service_file="/etc/systemd/system/voicerecognisebot.service"

# Create the service unit file
cat <<EOL > "$service_file"
[Unit]
Description=VoiceRecogniseBot Command After Network is Up
After=network-online.target

[Service]
ExecStart=/usr/bin/VoiceRecogniseBot --command bot
Restart=always
RestartSec=5
User=voicebot

[Install]
WantedBy=multi-user.target
EOL




# Reload the systemd daemon to update the service list
systemctl daemon-reload

# Enable the service to start automatically on boot
systemctl enable voicerecognisebot.service

# Start the service immediately
systemctl start voicerecognisebot.service

sudo useradd voicebot
echo "VoiceRecogniseBot service has been configured and started."

echo -e "\nEnjoy using VoiceRecogniseBot!"


